cups: added Paul Smedleys' patches and more build patches.
git-svn-id: http://svn.netlabs.org/repos/ports/cups/trunk@715 8d6eb4b1-0faa-de11-b929-00e081727c95

diff --git a/install-sh b/install-sh
--- a/install-sh
+++ b/install-sh
@@ -209,7 +209,7 @@ else
 	# Update permissions and strip as needed, then move to the final name.
 	# If the chmod, strip, rm, or mv commands fail, remove the installed
 	# file...
-	if [ x"$stripcmd" != x ]; then $doit $stripcmd $stripopt "$dsttmp" || echo "warning: Unable to strip $dst!"; fi
+	#if [ x"$stripcmd" != x ]; then $doit $stripcmd $stripopt "$dsttmp" || echo "warning: Unable to strip $dst!"; fi
 	if [ x"$chowncmd" != x ]; then $doit $chowncmd "$dsttmp" || echo "warning: Unable to change owner of $dst!"; fi
 	if [ x"$chgrpcmd" != x ]; then $doit $chgrpcmd "$dsttmp" || echo "warning: Unable to change group of $dst!"; fi
 
